name: CI of Linux
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: docker-compose --file cppcheck/docker-compose.test.yml build
      - name: test
        run: docker-compose --file cppcheck/docker-compose.test.yml run sut
