name: CI of Windows
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          docker-compose --version
          docker build -t vs2019 vs/vs2019
